name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    services:
      cypress:
        image: cypress/browsers:node16.19.1-chrome116-ff116
        options: >-
          --shm-size=2g
        ports:
          - 5900:5900

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

